### PR TITLE
Purchase links, percentages, links section styling & some minor tweaks

### PR DESCRIPTION
**Pull request by brianhernandez**
Hey Oscar.  Here are my parts of the projects so far, and some of the tweaks I've made to your framework you setup for us.  The framework you setup was great, it was fairly easy for me to enter my parts.  There are some spacing tweaks that I may need your help with though.  And I still need to work on the overlay part of the third book entry which I will work on tomorrow.  For now though, here are my change notes I took for this pull request:
- Bumped the font size for the meta-data information under the book titles to .875em as the mockup looks like they are at 14px here.
- To add the purchase book links (via Amazon, Gumroad etc.), I put them after a div that I wrapped the contexts within the `.bookEntry` around.  So the `.bookEntry` contains the original content in the first div, then after that the links to where you can buy the book or download it are in the second div.  I am thinking this might be useful in the future to contain everything about a single book in one `.bookEntry` div, as opposed to having these purchase links come after `.bookEntry` div.  Let me know what you think though.
- The Nav bar font I changed to Roboto instead of Roboto Slab as the mockup looks like they are using a sans-serif font here.
- Tweaked the search bar font, sizing and search button sizing.  I had to insert the magnifying glass image inside of a div with the `.dem` class CSS stylings.  The magnifying glass image was getting distorted because the `.dem` styling isn't a perfect square as shown in the mockup.  So, by putting the image inside of the `.dem` div I was also able keep its proper proportions.  This also allowed me to resize the magnifying glass which is shown smaller in the mockup than the actual size that the file comes in.  As a result, the the margin between the search bar and navigation has shortened.  Can you help me widen this, I think you understand better how this grid is setup and I was having an issue with changing it.  The search bar should be widened too, as in the mockup it begins before the book icon above it.
- I changed the `.logoContainer` and the `.incContainer` to have 3em margins on their left and right sides respectively.  This is to match and track the book entry edges on their left and right sides as shown in the mockup.
- I added a `border-radius` to the `.bookEntry` class and to the `.bookImg` class as they look like they have a 3px `border-radius` in the mockup.
- Added the percentage bars and styled the links section.
- Random but I edited the `coverEloquent.png` image to exactly match the image in the mockup.  Lol, totally not necessary but it was easy.

### CODE REVIEW

**Comment by OscarRobertRodriguez** [comment]
It looks good. I see what  your talking about the search bar sizing I'll work on that and yes it makes sense to me for the links to be included in the `bookEntry` div.   I guess i'll edit it from here  before we merge to master i'll push to your branch on my local repo and the changes will show up here than we will merge to the master

**Comment by OscarRobertRodriguez** [comment]
ok I made my changes pull them into your branch and take a look. Everything else looks good. I brought the margin up and also raised the header up. I made changes to the nav links font-weight as it seemed heavier in the mockup. 

what do you think about the bottom footer does the text seem off with spacing from the sides should i bring the text in more.  Good job with the third book entry that look hard.

**Comment by brianhernandez** [comment]
Cool, this is looking awesome man.  

So, I had pushed the footer's icon and copyright information out to be 3ems from the edges of my browser because on my screen that is the same margin that was being calculated on the sides of each `.bookEntry` div for me.  But, I realized these margins are `auto` calculated so they may not always be 3ems on other screens and you may be seeing something different.  So instead I wrapped the `.logoContainer` class and the `.incContainer` class in a `.footWrapper` class with a width of 74ems to match the `.bookEntry` div then gave this `.footWrapper` class auto margins for the sides.  So, now it should always be in line and the same with with the `.bookEntry` classes above.  It looks fine to me.  Let me know what you think.  

The only other issue I can see with the project now is the placeholder color text for the overlay context search (third book entry) is green like the header search bar.  We need that header search bar to have that green color but I don't know how we could make the context search placeholder text black at the same time since we are declaring the color with the `-browservenderprefix-placeholder: { }`  I guess I'll ask the QA to see if there is a way around this.

**Comment by OscarRobertRodriguez** [comment]
looks good but i do see what you mean with the placeholder on the third entry maybe we can make a separate class with the prefix. And i don't know if it shows up on yours but I'm seeing blue for ght bookmark it icon and text and also the prices in the buttons are blue.

**Comment by OscarRobertRodriguez** [comment]
i think i found a solution for the placeholder text i'll push it to this request

**Comment by brianhernandez** [comment]
Oh cool.

I fixed the blue colors on the bookmark icons and prices.

**Comment by OscarRobertRodriguez** [comment]
ok i fixed the placeholder color looking at your fix now

**Comment by OscarRobertRodriguez** [comment]
yeah your fix seems to have corrected the color issue. I don't see anything else wrong. I think we can merge now. do you see anything else?

**Comment by brianhernandez** [comment]
I think it looks pretty good.  I am just cleaning up some stuff with the code hang on.

**Comment by OscarRobertRodriguez** [comment]
okay

**Comment by brianhernandez** [comment]
Ok, this looks pretty perfect to me.  All I did was just cleaned up some spacing in the code.  Nudged the magnifying glass down to make it look more centered and changed the width of the tab content overlay.  But if it looks off on your end you can change it.  I think there may be some things that might look off between our screens perhaps.

**Comment by OscarRobertRodriguez** [comment]
no still looks good to me i think we can merge it what do you think

**Comment by brianhernandez** [comment]
Yup.  I think it is all set to merge too!  You can do the honors if you want.

**Comment by OscarRobertRodriguez** [comment]
okay here we go

**Comment by OscarRobertRodriguez** [comment]
okay im going back to my branch

**Pull request merged**
