### PR TITLE
Added the content bubbles in first book entry above progress bars.

### PR DESCRIPTION
**Pull request by brianhernandez**
Hey Oscar.  I had realized I totally forgot about those content bubbles that are above the progress bars in the first book entry.  I've added them.  Take a look when you get a chance.  I also finished my articles.  Finally, what is the github pages link to our live project?  -Brian

### CODE REVIEW

**Comment by OscarRobertRodriguez** [comment]
okay i'll take a look. You can find the github pages live link under settings then scroll down to github pages  and you should see a link right there.

**Comment by brianhernandez** [comment]
What settings do you mean?  What page am I looking for settings on?

**Comment by OscarRobertRodriguez** [comment]
well your talking about the live link to this repo right?

**Comment by brianhernandez** [comment]
The link to be able to see what we actually made in the browser.  That goes to the index.html file on github pages.  I went to h[ttps://oscarrobertrodriguez.github.io/teamProject1/](https://oscarrobertrodriguez.github.io/teamProject1/) and it looks like that is an older version when we first started working on the project.

**Comment by OscarRobertRodriguez** [comment]
oh yeah that is old well I have to merge it with master I'll do that right now

**Comment by OscarRobertRodriguez** [comment]
okay there it goes we have to remember to merge with master or else it won't update

**Comment by OscarRobertRodriguez** [comment]
I've looked at your code it looks good I don't know how we missed that but oh well you fixed it now.
Merge it whenever your ready.

**Comment by brianhernandez** [comment]
Ok cool.  I will do it now then.

**Comment by OscarRobertRodriguez** [comment]
okay  ill merge gh-pages

**Comment by OscarRobertRodriguez** [comment]
okay the live site is up to date

**Comment by brianhernandez** [comment]
Cool, nice work!  I guess we can hand in the project then.

**Comment by OscarRobertRodriguez** [comment]
okay let me do the something real quick

**Comment by brianhernandez** [comment]
Ok sure.

**Comment by OscarRobertRodriguez** [comment]
So do we both submit separately or do we submit together

**Comment by brianhernandez** [comment]
I think when we both know it is all good to go we can click the button.

**Pull request merged**
